│ > The unsync service seems not to work... No errors, but the actual folder         │
│   remains, and nothing happens. In the log files I see this: "14 Aug 12:47:00AM    │
│   ERROR /home/nando/odrive-agent-mount/GDrive Personale/Registrazioni Personali    │
│   was unable to be successfully unsynced via user action due to Unsync             │
│   subscription missing.". Please modify the .desktop file introducing a script     │
│   that calls the python unsync method than show a popup with error message if      │
│   this happens  